[package]
name = "policy"
version = "0.1.0"
edition = "2021"
authors.workspace = true

[dependencies]
bullet_core = { package = "bullet_core", git = 'https://github.com/jw1912/bullet', rev = "10a67249103881932cc48b1ec7f4c5ffb652eebc" }
bullet_cuda_backend = { package = "bullet_cuda_backend", git = 'https://github.com/jw1912/bullet', rev = "10a67249103881932cc48b1ec7f4c5ffb652eebc" }
montyformat = "0.9.0"